squat/kilo

- manifests/kilo-k3s-flannel.yaml
- manifests/kilo-k3s.yaml
feat: Change the kubeconfig hostPath, if k3s agent node just runs in splited mode.
> Change the kubeconfig hostPath, if k3s agent node just runs in splited mode.

- README.md
- docs/annotations.md
- pkg/calico/calico
- pkg/encapsulation/none.go
- pkg/k8s/backend.go
- pkg/k8s/backend_test.go
- pkg/mesh/graph.go
- pkg/mesh/ip.go
- pkg/mesh/mesh.go
- pkg/mesh/mesh_test.go
- pkg/mesh/topology.go
- pkg/mesh/topology_test.go
- pkg/wireguard/conf.go
- pkg/wireguard/conf_test.go
This commit allows DNS names to be used when specifying the endpoint
for a node in the WireGuard mesh. This is useful in many scenarios, in
particular when operating an IoT device whose public IP is dynamic. This
change allows the administrator to use a dynamic DNS name in the node's
endpoint.
One of the side-effects of this change is that the WireGuard port can
now be specified individually for each node in the mesh, if the
administrator wishes to do so.
*Note*: this commit introduces a breaking change; the
`force-external-ip` node annotation has been removed; its functionality
has been ported over to the `force-endpoint` annotation. This annotation
is documented in the annotations.md file. The expected content of this
annotation is no longer a CIDR but rather a host:port. The host can …
> pkg/mesh,pkg/wireguard: allow DNS name endpoints

- cmd/kgctl/graph.go
- cmd/kgctl/showconf.go
- docs/annotations.md
- pkg/k8s/apis/kilo/v1alpha1/openapi_generated.go
- pkg/k8s/apis/kilo/v1alpha1/types.go
- pkg/mesh/mesh.go
- pkg/mesh/topology.go
- pkg/mesh/topology_test.go
- pkg/wireguard/conf.go
This PR documents the use of the persistent-keepalive annotation and
corrects the implementation of keepalives.
This PR also changes how Kilo allows nodes and peers behind NAT to roam.
Rather that ignore changes to endpoints when comparing WireGuard
configurations, Kilo now incorporates changes to endpoints for peers
behind NAT into its configuration first and later compares the
configurations.
Fixes: https://github.com/squat/kilo/issues/34#issuecomment-594130539
> pkg/mesh,pkg/wireguard: update NAT endpoints

- docs/vpn-server.md
- docs/vpn.md
This commit introduces a new document explaining how peers can use the
Kilo cluster VPN as a gateway to the internet.
Fixes: #40
> docs/vpn: document vpn as internet gateway

- README.md
This commit removes a code snippet that is specific to CoreOS Container
Linux. Including this in the installation instructions for WireGuard can
give the impression that this code works for any cluster.
Fixes: #89.
> README.md: remove CoreOS-specific install step

- pkg/mesh/mesh.go
This ensures that Kilo will not select an IP assigned to the Kilo
interface when discovering public and private IPs.
> pkg/mesh/mesh.go: ignore Kilo IP during discovery

- pkg/mesh/graph.go
This commit changes the graph so that the WireGuard CIDR is used as the
title rather than the pod subnet assigned to a node in the cluster.
> pkg/mesh/graph.go: use WireGuard CIDR as title

- pkg/mesh/mesh.go
- pkg/mesh/routes.go
Add default iptables to allow forward traffic from and to pod cidr.
Previously Kilo expected the default behaviour of the forward chain to
accept packets, which can not be guaranteed.
> BUG: iptables rules

- pkg/mesh/mesh.go
This commit fixes a bug where the variable holding the index of the
private interface was shadowed, causing it to always be "0".
> pkg/mesh: don't shadow privIface

- .github/workflows/release.yaml
- Makefile
All kgctl will be published on each new release.
The naming convention for the binaries is kgctl-<os name>-<architecture>.
Solves #56
> .github/workflows/ci.yml: publish binaries

- pkg/mesh/routes.go
#106 added these rules under the assumption that Kilo should automatically allow traffic going from/to the pods.
What this actually did was break all firewalls that are "accept explicit, drop implicit" style and allow all traffic through the firewall.
If a user has configured their firewall to be drop by default, they should add rules like these manually if they want to allow all traffic.
This also breaks network policy controllers that are written/configured this way.
> Vulnerability: Don't add generic ACCEPT rules to the filter chain

- pkg/mesh/mesh.go
Because of new naming conventions for locations, the CIDRs were not
being set within locations.
This lead to no iptables rules added for nodes in the same location.
> pkg/mesh/mesh.go: iptables rules in encapsulation

- MAINTAINERS.md
This commit proposes [Leon](https://github.com/leonnicolas) as a
maintainer of Kilo. Leon has done tons of great work in the project in
feature development, bug triaging, and documentation. It would be a
privilege to have you join!
cc @leonnicolas :whale:
> MAINTAINERS.md: propose @leonnicolas as maintainer

- docs/kgctl.md
Let's make the documentation more inclusive and sensitive of the
familiarity and comfort of users.
> docs: remove use of 'simply'

- pkg/iptables/fake.go
- pkg/iptables/iptables.go
- pkg/iptables/iptables_test.go
- pkg/iptables/rulecache.go
- pkg/iptables/rulecache_test.go
- pkg/mesh/mesh.go
- pkg/mesh/routes.go
Currently, every time the iptables controller syncs rules, it spawns an
an iptables process for every rule it checks. This causes two problems:
1. it creates unnecessary load on the system; and
2. it causes contention on the xtables lock file.
This commit creates a lazy cache for iptables rules and chains that
avoids spawning iptables processes. This means that each time the
iptables rules are reconciled, if no rules need to be changed then at
most one iptables process should be spawned to check all of the rules in
a chain and at most one process should be spawned to check all of the
chains in a table.
Note: the success of this reduction in calls to iptables depends on a
somewhat fragile comparison of iptables rule text. The text of any rule
must match exactly, including the order of the …
> pkg/iptables: reduce calls to iptables

- manifests/kilo-kubeadm.yaml
As discussed in
https://github.com/squat/kilo/issues/129#issuecomment-789651850,
the Kilo manifests for kubeadm install the CNI configuration in the
wrong directory. They are using /etc/kubernetes/cni/net.d [0] when they
should be using /etc/cni/net.d [1].
[0]
https://github.com/squat/kilo/blob/main/manifests/kilo-kubeadm.yaml#L163
[1]
https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins/#cni
> manifests: fix kubeadm CNI path

- pkg/mesh/ip.go
- pkg/mesh/ip_test.go
Currently Kilo incorrectly identifies the 172.16/12 private IP range.
This commit fixes the logic.
Fixes: https://github.com/squat/kilo/issues/57#issuecomment-791450130
> pkg/mesh: correctly idenitfy 172.16/12 IPs

- pkg/encapsulation/ipip.go
- pkg/encapsulation/ipip_cgo.go
- pkg/encapsulation/ipip_nocgo.go
Since #116 implemented fragile comparisons of iptables rules to avoid
calling the iptables binary excessively during every reconciliation, the
iptables rules for IPIP encapsulation must be updated to match the
expected output. One complication is that rather than returning the
protocol number in the rule, iptables resolves the protocol number to a
name by looking up the number in the netd protocols database. This name
can vary depending on the host's environment. This commit adds two
solutions for resolving the protocol name:
1. a fixed mapping to the string `ipencap`, which should always work
for Kilo whenever it runs in the Alpine Linux container; and
2. a runtime lookup using the netd database, which only works if Kilo is
compiled with CGO and is meant to be used only if Kilo is not …
> pkg/encapsulation/ipip*: fix ipip iptables rules

- pkg/mesh/mesh.go
resync period was not added to mesh struct.
fixes #137 
> pkg/mesh/mesh.go: actually add resync period

- pkg/encapsulation/ipip.go
One ipip iptabels rule was still not in the right order.
> pkg/encapsulation/ipip.go: fix order of flags

- pkg/k8s/backend.go
- pkg/k8s/backend_test.go
- pkg/mesh/backend.go
- pkg/mesh/mesh.go
- pkg/mesh/topology.go
When forcing the internal IP to "" or "-" with the force-internal-ip annotation, private IPs won't be used.
Nodes that have the annotation will be put in their own location: e.g.: "node:node-name". Then they will try to use WireGuard to connect to other nodes' endpoints in the cluster over their public interface. This only works, if the kubelet of the respected nodes can still connect to the API server over a public endpoint. If the kubelet uses a private IP to connect to the API server, Kilo will create routes so that the kubelet's request to the API server will go over the WireGuard interface. This leading to the node being  not ready, if the API server's node has not set up the WireGurad config correctly. Anyways, trying to encrypt API server communication over Kilo's WireGuard sounds …
> FEATURE: allow disabling private IPs

- pkg/mesh/graph.go
- pkg/mesh/mesh.go
- pkg/mesh/topology.go
- pkg/mesh/topology_test.go
Commit 4d00bc56fea264940195562affb23c31378800fe introduced a bug in the
Kilo graph generation logic. This commit used the WireGuard CIDR from
the topology struct as the graph title, however this field is nil
whenever the selected node is not a leader, causing the program to
panic.
This commit changes the meaning of the topology struct's wireGuardCIDR
field so that the field is always defined and the normalized value will
always be equal to the Kilo subnet CIDR. When the selected node is a
leader node, then the field's IP will be the IP allocated to the node
within the subnet. This effectively prevents the program from panicking.
> pkg/mesh: fix panic in graph

- pkg/mesh/graph.go
Previously the newlines were ignored by circo.
This lead to very flat ellipses.
Masked newlines "\\n" are correctly handeled.
> pkg/mesh/graph.go: fix format

- pkg/route/route.go
Currently, when the route controller processes updates from netlink, it
checks if the routes in the table are nil or have no destination.
However, we control this and can guarantee that it's never the case.
Instead, we should check if the routes from netlink are valid.
> pkg/route: correct route error check

- manifests/kilo-bootkube-flannel.yaml
- manifests/kilo-bootkube.yaml
- manifests/kilo-k3s-flannel.yaml
- manifests/kilo-k3s-userspace-heterogeneous.yaml
- manifests/kilo-k3s-userspace.yaml
- manifests/kilo-k3s.yaml
- manifests/kilo-kubeadm-flannel.yaml
- manifests/kilo-kubeadm.yaml
- manifests/kilo-typhoon-flannel.yaml
- manifests/kilo-typhoon.yaml
This commit ammends all of the Kilo manifests so that the DaemonSets
declare the port they expose.
> manifests: declare metrics port

- README.md
Clarify pod network connectivity within cluster that spans across multiple networks, including networks behind NAT.
A more detailed documentation will follow about how to use UDP hole punching in Kilo.
"Resolves" #156 
> README.md: mention pod network connectivity behind NAT

- Makefile
- cmd/gen-docs/main.go
- docs/api.md
- pkg/k8s/apis/kilo/v1alpha1/types.go
- website/docs/api
- website/sidebars.js
The new make command `make gen-docs` is introduced.
It will build a markdown file from the CRD introduced by Kilo.
The generation of the docs is a requirement for building the website.
> cmd/gen-docs/main.go: auto generate docs for CRD

- Makefile
- README.md
- cmd/docs-gen/main.go
- docs/api.md
- pkg/k8s/apis/kilo/v1alpha1/openapi_generated.go
- pkg/k8s/apis/kilo/v1alpha1/types.go
This commit cleans up some typos in the documentation, clarifies some
explanations, fixes a bash script that would not expand a variable, and
renames the API documentation generator command from gen-docs to
docs-gen to match the output binary name.
> docs,README.md: clean up documentation

- .github/workflows/ci.yml
- Makefile
- e2e/helper-curl.yaml
- e2e/kilo-kind-userspace.yaml
- e2e/kind-config.yaml
- e2e/kind.sh
Tests are using kind, adjacency and bash_unit and a container with curl.
A kind cluster is spun up and the previously build container image of
Kilo is loaded into it.
Adjacency and a curl container is started.
From the curl container a http request is send to the adjacency service.
The test fails if curl returns an unexpected result.
Two test are run. One with `mesh-granularity=full` and `location`.
> Makefile, e2e/*: Add end to end tests

- Makefile
This will only affect `website/docs/api.md` and we won't break any other things by accident. There won't be any escaped code blocks in this file, that can break with this approach.
> Makefile: workaround to fix broken markdown link in website

- .github/workflows/ci.yml
- .github/workflows/release.yaml
- Makefile
This commit bumps the Golang toolchain version used to build Kilo to go
1.16 to support builing kgctl for the arm64 M1 macs.
> Makefile: bump golang toolchain for M1 support

- Makefile
- e2e/kind.sh
This commit refactors the e2e tests in the following ways:
* bump the version of `bash_unit` to 1.7.2: the previous version was
from 2018;
* remove the unused `block` function;
* fix the order of `block_unitil_ready_by_name` and `check_ping`: we
should not attempt to interact with pods before they are considered
ready;
* extract the retry logic into a reusable function called `retry`; and
* retry the `check_adjacent` function for robustness.
> e2e: refactor the end to end tests

- Makefile
- e2e/kilo-kind-userspace.yaml
- e2e/kind-config.yaml
- e2e/kind.sh
This commit adds testing of the VPN feature of Kilo to the e2e tests.
Also, in order to make the tests less flaky, this commit ensures that
the Kilo Pods use the "root" kubeconfig to connect to the API rather
than the Kubernetes API's cluster IP, which can become unavailable when
networking is reconfigured.
> e2e: test VPN in e2e tests

- cmd/kgctl/main.go
This commit adds better handling of the default kubeconfig location in
the kgctl binary for cases where the `$KUBECONFIG` environment variable
is not set. In these cases, kgctl will default to
`$HOME/.kube/config`, putting it in line with tools like `kubectl` and
`kind`.
> cmd/kgctl: improve default kubeconfig

- cmd/kgctl/graph.go
- cmd/kgctl/showconf.go
- docs/annotations.md
- pkg/k8s/backend.go
- pkg/mesh/backend.go
- pkg/mesh/mesh.go
- pkg/mesh/routes.go
- pkg/mesh/routes_test.go
- pkg/mesh/topology.go
- pkg/mesh/topology_test.go
Users can specify IPs with the annotation "allowed-location-ips".
It makes no difference which node of a location is annotated.
The IP should be routable from the particular location, e.g. a printer in
the same LAN.
This way these IPs become routable from other location.
> pkg/: FEATURE: support allowed IPs outside a cluster

- e2e/kind.sh
The recent test refactor wrapped the adjacency check in a `retry`,
however, the `check_adjacent` function had an `assert` in it, which
meant that the test would fail immediately and not be retried. This
PR moves the assertion out of the check, which also allows for
improved code reuse.
This PR also adds an e2e test that ensures that invalid Kilo Peers are
rejected thanks to the improved OpenAPI v3 validation.
> e2e test improvements

- e2e/helper-curl.yaml
- e2e/kind.sh
This commit adds a new e2e test fot the recently introduced
allowed-location-ips annotation. This test annotates two nodes with
allowed IPs and then ensures that both of these IPs are reachable from
the curl helper Pod. We need to annotate two nodes because there is a
chance that the curl Pod is scheduled to the annotated node, in which
case we would not test the full functionality.
> e2e: add test for allowed location IPs

- Makefile
- e2e/full-mesh.sh
- e2e/lib.sh
- e2e/location-mesh.sh
This commit splits the e2e tests into different suites that all reuse
helper functions from the lib.sh file. This split ensures that the tests
within a suite can all have the same setup, e.g. all tests depending on
a full-mesh will be set up with a full-mesh, and is resilient against
changes in test ordering.
> e2e: split e2e tests into different suites

- cmd/kgctl/graph.go
- cmd/kgctl/main.go
- cmd/kgctl/showconf.go
- e2e/full-mesh.sh
- e2e/lib.sh
- e2e/location-mesh.sh
- pkg/k8s/backend.go
- pkg/mesh/backend.go
- pkg/mesh/mesh.go
Addes granularity annotation to auto detect the mesh granularity when
using `kubectl`
> pkg/ cmd/: kgctl autodetect mesh granularity

- Makefile
We seem to be running into
https://github.com/kubernetes-sigs/kind/issues/2240: kube-proxy is
crashlooping, which in turn causes CoreDNS to fail to connect to the API
server over the Service CIDR, which in turn cases DNS resolution to fail
in the cluster, which in turn causes the e2e tests to fail.
To address this,
this commit bumps the kind version to 0.11.1.
> Makefile: fix e2e tests

- .gitignore
- Makefile
- e2e/full-mesh.sh
- e2e/location-mesh.sh
- e2e/setup.sh
- e2e/teardown.sh
Currently, each test suite spins up its own kind cluster, which results
in longer e2e test times as each test suite needs to wait for the
cluster to be ready and for images to download. This commit creates two
new virtual test suites that are run before and after the actual e2e
tests and are responsible for creating and destroying a kind cluster
respectively. Any test suite that needs a fresh cluster can still spin
up its own using the `create_cluster` helper in the lib.sh file.
> e2e: reuse kind cluster across suites

- e2e/full-mesh.sh
- e2e/kind-config.yaml
- e2e/lib.sh
- e2e/location-mesh.sh
- e2e/setup.sh
This pull request implements a few improvements to the e2e test suite separated by commit. In the future, these improvements will help us test mult-cluster services with multiple kind clusters.
1. This commit modifies the e2e shell scripts so that the KUBECONFIG
variable does not need to be exported. This will become important once
we allow the e2e test suite to launch multiple clusters, e.g. to test
multi-cluster connectivity.
2. This commit modifies the logic of the check_adjacent helper so that
rather than expecting the argument to be n^2+n it expects simply n. This
makes it easier to update the caller when the number of nodes in the
cluster changes.
3. This commit allows the kind cluster configuration to be parameterized at
call time. This enables the test suite to build multiple …
> e2e test suite improvements

- cmd/docs-gen/main.go
- docs/annotations.md
- docs/api.md
- docs/building_kilo.md
- docs/building_website.md
- docs/userspace-wireguard.md
This commit standardizes how we display a `note` in our docs.
Previously, we used a mix of `_Note_:`, `__Note:__`, `> Note`, and `>
**Note**:` among others. Now, all notes appear as `> **Note**:`.
> docs: use consistent notes

- .gitignore
- Makefile
- e2e/multi-cluster.sh
This commit adds a new test suite to the e2e tests that validates
multi-cluster connectivity in Kilo. This is really just an extension of
the testing of the Peers CRD and related tooling that also exercises the
`--allowed-ips` flag of the `kgctl` tool.
> Test multi cluster

- e2e/kilo-kind-userspace.yaml
- manifests/kilo-bootkube-flannel.yaml
- manifests/kilo-bootkube.yaml
- manifests/kilo-k3s-flannel.yaml
- manifests/kilo-k3s-userspace-heterogeneous.yaml
- manifests/kilo-k3s-userspace.yaml
- manifests/kilo-k3s.yaml
- manifests/kilo-kubeadm-flannel.yaml
- manifests/kilo-kubeadm.yaml
- manifests/kilo-typhoon-flannel.yaml
- manifests/kilo-typhoon.yaml
Since Kilo now uses the `kilo.squat.ai/discovered-endpoints` annotation
for Peer discovery, Kilo no longer needs to update Peer resources, so we
can remove this permission from the ClusterRole. Note, the RBAC in the
manifests is not used today, but we eventually want to migrate to this.
xref: #210
> manifests,e2e: reduce cluster role permissions

- manifests/kilo-k3s-flannel.yaml
- manifests/kilo-k3s-userspace-heterogeneous.yaml
- manifests/kilo-k3s-userspace.yaml
- manifests/kilo-k3s.yaml
This PR adjusts the K3S manifests to automatically generate a kubeconfig file which is used by `kg` based on the token of the kilo ServiceAccount and the master address found in the kubelet's kubeconfig file.
The eliminates the need of manually copying `/etc/rancher/k3s/k3s.yaml` from the master to all agent nodes.
At the same time, the kg daemon only has the permissions granted to its ServiceAccount instead of a full cluster access.
Closes #49
> k3s: Dynamically generate kubeconfig

- cmd/kg/main.go
- pkg/mesh/mesh.go
- pkg/wireguard/wireguard.go
This commit makes it possible to configure the MTU for the WireGuard
interface created by Kilo.
Fixes: #208
> pkg/wireguard: allow configuring MTU

- Dockerfile
- Makefile
- cmd/kg/handlers.go
- cmd/kg/main.go
- e2e/handlers.sh
Closes #23
@squat , @leonnicolas: I am not too happy about the code-duplication for creating a `mesh.Topology` instance.
At the same time, I am lacking the deeper insight into Kilos code-base to understand where we could put this code.
I was thinking about a function `mesh.Backend.Topology()` or `mesh.Mesh.Topology()`.
I guess the main question would be then weather we want to query the current topology directly from the backend or if we take the current state from the mesh object?
> kg: add new handler for rendering the topology graph via the metrics webserver

- e2e/lib.sh
adjacency is running in the default namespace.
Prior to this commit the block_until_ready function
received the adjacency namespace instead of the default
namespace as a parameter.
> e2e/lib.sh: fix namespace of adjacency

- manifests/crds.yaml
- pkg/k8s/apis/kilo/v1alpha1/types.go
When updating Kilo to the latest version of the CustomResourceDefinition
API, the Kilo Peer CRD was incorrectly scoped as a namespaced resource
due to differences in the ergonomics of the tooling.
This commit fixes the scoping of the Peer CRD to be cluster-wide.
> pkg/k8s: fix resource scope of Kilo CRD

- pkg/mesh/discoverips.go
There are times when the loopback address can show up in the list of public addresses kilo will use to set a node's endpoint
Following on from
https://github.com/squat/kilo/issues/229#issuecomment-903252431
> filter local IP addresses when scanning for ips resolved by hostname

- manifests/peer-validation.yaml
Use a maintained fork of certgen.
The former project is not maintained anymore and will not work for
Kubernteses v1.22 because the admission v1beta1 API was dropped.
See [here](https://github.com/jet/kube-webhook-certgen/pull/32)
Also fix the name of the liste-metrics flag.
> manifests/peer-validation.yaml: fix image and flag

- cmd/kgctl/main.go
`cobra` automatically prints and error if `runE` returns an error.
Since we explicitly print the error, we need to silence cobra.
> cmd/kgctl/main.go: suppress second error message

- docs/kgctl.md
I've created a package in Arch User Repository for easily installing `kgctl` on Archlinux via an AUR helper like `yay` or `paru`. This internally fetches the binaries from [the GitHub releases page](https://github.com/squat/kilo/releases)
Related Links:
- https://aur.archlinux.org/packages/kgctl-bin
- https://github.com/codingCoffee/PKGBUILDs
Signed-off-by: Ameya Shenoy <shenoy.ameya@gmail.com>
> docs: kgctl binary install on Archlinux

- cmd/kg/main.go
- pkg/mesh/mesh.go
Optionally prefer a node's external IP be set to it's private IP
> If deploying a cluser to a cloud provider across regions with a shared VPC, I'd probably want my traffic to stay inside the VPC to limit any bandwidth egress charges or slower links
https://github.com/squat/kilo/issues/229#issuecomment-903252431
> pkg/mesh: optionally prioritise private addresses

- .github/workflows/ci.yml
- go.sum
This commit adds a stage to the GitHub Actions CI workflow to verify
that vendor and go.mod/sum are always up-to-date. If the vendored files
require any changes then CI will fail. This ensures that the repo
remains the source of truth.
> .github/workflows: ensure vendor is clean

- cmd/kg/main.go
- pkg/mesh/mesh.go
- pkg/mesh/routes.go
Some linux distros or docker will set the default policy in the FORWARD
chain in the filter table to DROP. With the new ip-tables-forward-rules
flag a generic ACCEPT for all packages going from and to the pod subnet
is added to the FORWARD chain.
Fixes #241
> pkg/mesh/routes.go: add flag for generic ACCEPT in FORWARD chain

- pkg/mesh/routes.go
- pkg/mesh/topology.go
Before this commit (see #241 and #244) we added the forward ALLOW rule only for the node's
pod CIDR  and not all pod CIDRs of a location. This commit adds the
forward ALLOW rule for packages from (source) and to (destination) all
pod CIDRs of the location if the node is a leader node.
> pkg/mesh/routes.go: add iptbales forward allow rules for segment.

- pkg/iptables/iptables.go
This commit enhances the iptables controller to disable reconciliation
of IPv6 rules whenever it detects that IPv6 is disabled in the kernel,
in order to fix #259.
cc @aholler
> iptables: allow disabling IPv6

- pkg/mesh/mesh.go
Partial fix for #273
Before, you were generated a shared key rather than a private key which is slightly different.
This caused inconsistencies when trying to set the key.
> Fix private key generation code

- pkg/mesh/mesh.go
Partial fix for #273
The equality checks were broken in #239 and this fixes them.
The issue where the private keys do not match is not fixed by this PR though and I could only fix that by changing the keys on disk manually to match the key that wireguard was converting it to...
> Fix peer and node equality checking

- pkg/mesh/routes.go
Currently, when a node is behind NAT, it is possible that routes to the
node's private IP address, i.e. routes necessary to communicate with the
Kubelet and any Pods on the host network, will not be created because
the private IP is seen as the same as the location's endpoint and is
thus skipped because trying to encapsulate traffic to the endpoint would
break communiation with the endpoint itself.
This logic is not correct for nodes that are behind NAT, because the
endpoin that the node reports may not be the same as the discovered
endpoint for the location. Instead, we should compare the private IP
address to the discovered endpoint.
> pkg/mesh: fix routes for NATed nodes

- pkg/k8s/backend.go
- pkg/k8s/backend_test.go
Right now, the persistent keepalive field of the Peer CRD is always
interpretted as nanoseconds and not seconds. This causes a mismatch
between Kilo's expected behavior and the actual interval that is given
to Peers. Because the interval is interpretted as nanoseconds the value
rounds down to 0 seconds.
> backend: fix Peer persistent keepalive

- pkg/mesh/topology.go
Currently, when rendering the configuration for a Peer, the allowed
location configs of any segment are erroneously ignored, meaning that an
administrator will have to manually edit the configuration to get the
expected behavior from a Peer. This commit fixes the generation of the
configuration.
> pkg/mesh: respect allowed location IPs in peers

- .github/workflows/ci.yml
Currently, CI only runs for PRs to the main branch. This commit modifies
the configuration so that it runs for PRs to any branch.
> CI: run for all PRs

- .github/workflows/release.yaml
Currently,the job to build kgctl binaries is named `linux`, which
suggests to the reader that the job is only building binaries for Linux,
when it is in fact building binaries for Linux, Darwin, and Windows.
> .github/workflows/release.yaml: clarify job name

- e2e/kilo-kind-userspace.yaml
- manifests/kilo-bootkube.yaml
- manifests/kilo-k3s-userspace-heterogeneous.yaml
- manifests/kilo-k3s-userspace.yaml
- manifests/kilo-k3s.yaml
- manifests/kilo-kubeadm-userspace.yaml
- manifests/kilo-kubeadm.yaml
- manifests/kilo-typhoon.yaml
As mentioned in the Kilo Slack [0], Kubernetes supports CNI 0.4.0 and
does not yet support 1.0.0. Correspondingly, this commit downgrades the
declared CNI version in the configuration to 0.4.0 and crucially updates
the configuration used in the e2e tests to exercise this new CNI
version.
[0] https://kubernetes.slack.com/archives/C022EB4R7TK/p1650455432970199?thread_ts=1650368553.132859&cid=C022EB4R7TK
> manifests: use CNI 0.4.0

- .github/workflows/ci.yml
- Makefile
- docs/kg.md
This commit updates the CI configuration for Kilo to ensure that the
documentation, specifically the generated docs, are up-to-date.
> .github: ensure docs are up to date in CI

- Dockerfile
Currently, Kilo _only_ supports adding firewall rules via the legacy
iptables API. This means that on systems using nftables in the host
network namespace, the namespace will be polluted and both firewall
infrastructures will be used, causing unexpected and difficult
to predict interactions. In other words, networking may not work as
expected on nftables-based systems.
This PR fixes this by using the iptables-wrappers project [0] to install
run-time detection of the in-use iptables backend.
[0] https://github.com/kubernetes-sigs/iptables-wrappers
> Dockerfile: support nftables

- cmd/kg/main.go
- cmd/kgctl/main.go
- pkg/k8s/backend.go
- pkg/mesh/backend.go
- pkg/mesh/mesh.go
Remove almost all (except the ones created by informer-gen)
context.TODOs.
> Remove context.TODO()

- cmd/kg/main.go
- manifests/kilo-kubeadm-cilium.yaml
- pkg/encapsulation/cilium.go
- pkg/encapsulation/flannel.go
when cni management by kilo is disable, we can use existing cluster's cni setup thanks to add-on mode
https://kilo.squat.ai/docs/introduction#add-on-mode
this is a really basic implementation based on comment https://github.com/squat/kilo/issues/81#issuecomment-719809919
> feat: cilium add-mode support

- e2e/kilo-kind-userspace.yaml
- e2e/lib.sh
- manifests/kilo-k3s-userspace-heterogeneous.yaml
- manifests/kilo-k3s-userspace.yaml
- manifests/kilo-kubeadm-flannel-userspace.yaml
- manifests/kilo-kubeadm-userspace.yaml
Pin the image to a tag before boringtun's cli changed.
Specifically the --disable-drop-privileges flag need a boolean param.
> Pin boringtun image tag

- .github/workflows/ci.yml
The e2e tests are not flaky anymore, so we should run them daily to see
if they break for whatever reason. This way we notice before someone
makes a "goog" PR.
> .github/workflows/ci.yml: run e2e daily

- cmd/kg/main.go
- pkg/iptables/iptables.go
- pkg/iptables/iptables_test.go
- pkg/iptables/metrics.go
- pkg/mesh/mesh.go
To have better visibility of the iptables operations performed by kilo it would be nice to have prom metrics for them.
This PR introduces such metrics for all iptables operations by wrapping a proxy around the iptables client.
> Add metrics for iptables operations

- pkg/mesh/mesh.go
Only write private key to disk on new key generation. Otherwise just use what is there. This allows externally key generation and injection with a secret.
> Don't always write private key to disk

- e2e/kilo-kind-userspace.yaml
- e2e/lib.sh
- manifests/kilo-k3s-userspace-heterogeneous.yaml
- manifests/kilo-k3s-userspace.yaml
- manifests/kilo-kubeadm-userspace.yaml
A change in boringtun's cli caused the boringtun container to crash.
> e2e/kilo-kind-userspace.yaml: fix boringtun cli flags

- cmd/kg/handlers.go
- cmd/kg/main.go
- cmd/kgctl/connect_linux.go
- cmd/kgctl/graph.go
- cmd/kgctl/showconf.go
- docs/kg.md
- pkg/mesh/mesh.go
- pkg/mesh/routes.go
- pkg/mesh/topology.go
- pkg/mesh/topology_test.go
Currently, packets to service CIDRs may be masqueraded because they are
IP addresses that Kilo does not know about and therefore is not sure if
they know about some Kilo IPs, e.g. Peer IPs. This is not terrible but
it is annoying and can prevent some advanced use-cases, see #330. This
commit adds an optional flag to the `kg` binary that can be given
multiple times to specify the service CIDRs of the cluster so that Kilo
does not masquerade packets to them.
> pkg/mesh: avoid NAT-ing packets to service CIDRs

- cmd/kg/main.go
- docs/kg.md
- pkg/mesh/mesh.go
We've been looking into making kilo rollouts not resulting in a network-related downtime that's the result of cleanup on shutdown. From what I can tell almost all operations are already idempotent _anyway_.
The only issue i've been able to identify is the creation of the wireguard interface on startup - making that code path check for existence before trying to create a new one should prevent any issues there.
So far it's just an experiment, but I'd love to hear your thoughts on it!
> Make cleanup on shutdown optional

- .github/workflows/ci.yml
- .github/workflows/release.yaml
This commit updates the GitHub actions plugins to ensure that they all
use the new Node runtime, avoiding issues then the old Node runtime is
disabled.
> CI: update GitHub actions

- .github/workflows/ci.yml
This is probably not experimental anymore.
Hopefully now CI will be green.
> CI: stop enabling experimental docker features

- README.md
Uses updated URLs to fix the CI status badge.  More info available at https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge .
> Fix CI build status badge

- cmd/kg/main.go
- docs/kg.md
Added "cilium" which was missing in the help message.
```diff
-       --compatibility string           Should Kilo run in compatibility mode? Possible values: flannel
+       --compatibility string           Should Kilo run in compatibility mode? Possible values: flannel, cilium
```
> Polish help message

- Dockerfile
- Makefile
This makes it easy to run Kilo sidecars that connect a workload to a
mesh using `kgctl connect`.
Signed-off-by: squat <lserven@gmail.com>
> container: add kgctl binary

- cmd/kgctl/connect_linux.go
- docs/kgctl.md
- e2e/kgctl.sh
This commit makes the peer name argument in the `kgctl connect` command
optional. Now, the computer's hostname will be used as the default peer
name when no argument is supplied. This is a good predictable feature
that makes it easier to integrate with containers and environments like
Kubernetes.
Signed-off-by: squat <lserven@gmail.com>
> kgctl: make peer name argument optional

- Makefile
Bump the Alpine container base image to update the packages that are
installed at container build-time.
Fixes: https://github.com/squat/kilo/issues/388
Signed-off-by: squat <lserven@gmail.com>
> Docker: update iptables packages
