squat/kilo

pkg/mesh/mesh.go
pkg/wireguard/conf.go

This commit enables Kilo to ignore changes to the endpoints of peers
that sit behind a NAT gateway. We use the heuristic of a non-zero
persistent keepalive to decide whether the endpoint field should be
ignored. This will allow NATed peers to roam and for every node in the
cluster to have a different value for a peer's endpoint, as is natural
when a peer's connections are NATed.
Fixes #34 
Supersedes #37 
PTAL @carlosrmendes

pkg/wireguard: ignore changes to peers behind NAT

---

README.md
docs/kgctl.md

This commit introduces a new doc for the kgctl commandline tool.

docs/kgctl.md: add kgctl doc

---

manifests/kilo-k3s-flannel.yaml
manifests/kilo-k3s.yaml

Change path to kubeconfig to match k3s v1.0

---

manifests/kilo-k3s-flannel.yaml
manifests/kilo-k3s.yaml

Slipped my mind, but here's a quick comment to hopefully help people setup their kilo cluster on k3s without making the same mistakes I did :)

Add quick note for k3s setup

---

docs/multi-cluster-services.md

Highlighting Note in order to it visible first cause after analyzing some issues, i find people are ignoring this note section (including my self)

Highlighting Note

---

.github/workflows/ci.yml
README.md
docs/kg.md
docs/network-policies.md
docs/userspace-wireguard.md

This commit renames the principal branch of the repository to `main`!

*: rename branch to main

---

pkg/mesh/ip.go
pkg/mesh/ip_test.go

pkg/mesh: correctly check 172.16/12 IP range

---

website/package.json
website/yarn.lock

website: update docusaurus

---

docs/annotations.md

Add documentation for disable internal ip with the force-internal-ip annotation.

docs/annotations.md: docs for disable private ip

---

Dockerfile

Also extract them into arguments so it is easier to update

Dockerfile: Update CNI Plugins

---

pkg/mesh/mesh.go

This is more a request for comment, I don't think it changes much, but dropping useless code it always better for maintainability. I had a hard time with this part (especially thinking about feature 1 in #109) so I think I better share my analysis :
First the comment "so remove it from the mesh" is wrong / missleading as since 034c27a the delete in that if is not in there anymore.
Second the `m.nodes` map is not updated so setting `diff = true` will call `applyTopology` without any changes... which seams useless.
Third the rest of the code already checks for Ready so this special case here should not be needed.
Unless it's used to workaround some strange kube behaviour that I'm nor aware of, I don't see the need for those line with the current state of the rest of the code. 
The "received …

RFC: Remove syncNodes/syncPeers 'not Ready' special case 

---

pkg/k8s/apis/kilo/v1alpha1/types.go

pkg/k8s/apis/kilo/v1alpha1/types.go: add public key validation

---

README.md

README.md: add docker pulls badge

---

docs/peer-validation.md
website/docs/peer-validation
website/sidebars.js

docs/peer-validation: add docs about peer validation

---

docs/peer-validation.md

docs/peer-validation: fix code-block

---

website/package.json
website/yarn.lock

bump react, react-dom, docusaurus, classnames and dependencies (yarn.lock)

website/package.json: bump node_modules and update yarn.lock

---

README.md

Should we also add a communication section in the README.md, or save this for the future contributing section in the docs / website?

README.md: add slack badge

---

e2e/kind.sh

This commit fixes lint warnings produced by shellcheck. This simplifies
some of the `if`s and protects against variables with spaces. We may
want to consider shellchecking all scripts in the repo.

e2e/kind.sh: lint bash script

---

e2e/kind.sh

This file uses tabs everywhere instead of spaces, so fix the lines that
I added in the last PR.

e2e/kind.sh: make indentation consistent

---

.github/workflows/ci.yml

ci: add docker push in release ci

---

pkg/mesh/mesh.go
pkg/wireguard/conf.go
pkg/wireguard/conf_test.go
pkg/wireguard/wireguard.go

This will allow using more complex heuristics to select a nat endpoint.

Use LatestHandshake to validate endpoint

---

e2e/lib.sh

This commit updates the reference to the adjacency tool used in the e2e
tests.

e2e: update adjacency tool

---

docs/kg.md

docs: regenerate

---

docs/kgctl.md

docs: document installation with arkade

---

manifests/kilo-bootkube-flannel.yaml
manifests/kilo-bootkube.yaml
manifests/kilo-k3s-flannel.yaml
manifests/kilo-k3s-userspace-heterogeneous.yaml
manifests/kilo-k3s-userspace.yaml
manifests/kilo-k3s.yaml
manifests/kilo-kubeadm-flannel-userspace.yaml
manifests/kilo-kubeadm-flannel.yaml
manifests/kilo-kubeadm-userspace.yaml
manifests/kilo-kubeadm.yaml
manifests/kilo-typhoon-flannel.yaml
manifests/kilo-typhoon.yaml
manifests/peer-validation.yaml

pin release-0.4 image version to tag 0.4.0

---

.github/workflows/ci.yml
manifests/kilo-bootkube-flannel.yaml
manifests/kilo-bootkube.yaml
manifests/kilo-k3s-flannel.yaml
manifests/kilo-k3s-userspace-heterogeneous.yaml
manifests/kilo-k3s-userspace.yaml
manifests/kilo-k3s.yaml
manifests/kilo-kubeadm-flannel-userspace.yaml
manifests/kilo-kubeadm-flannel.yaml
manifests/kilo-kubeadm-userspace.yaml
manifests/kilo-kubeadm.yaml
manifests/kilo-typhoon-flannel.yaml
manifests/kilo-typhoon.yaml
manifests/peer-validation.yaml

Merge the release branch back into `main` to take all of the patches and tags.

Release 0.4

---

Dockerfile
manifests/kilo-bootkube.yaml
manifests/kilo-k3s-userspace-heterogeneous.yaml
manifests/kilo-k3s-userspace.yaml
manifests/kilo-k3s.yaml
manifests/kilo-kubeadm-userspace.yaml
manifests/kilo-kubeadm.yaml
manifests/kilo-typhoon.yaml

Untested, but per discussion on slack

bump CNI plugins version and fix spec version

---

manifests/kilo-bootkube-flannel.yaml
manifests/kilo-bootkube.yaml
manifests/kilo-k3s-flannel.yaml
manifests/kilo-k3s-userspace-heterogeneous.yaml
manifests/kilo-k3s-userspace.yaml
manifests/kilo-k3s.yaml
manifests/kilo-kubeadm-flannel-userspace.yaml
manifests/kilo-kubeadm-flannel.yaml
manifests/kilo-kubeadm-userspace.yaml
manifests/kilo-kubeadm.yaml
manifests/kilo-typhoon-flannel.yaml
manifests/kilo-typhoon.yaml
manifests/peer-validation.yaml

Merge release branch back into main.

Release 0.5

---

manifests/kilo-k3s-cilium.yaml

I love the work done to integrate kilo and cilium. For now my default stack for edge kubernetes is k3s + cilium + kilo.

ADD manifest for k3s with cilium as CNI

---

manifests/kilo-kubeadm-cilium.yaml

Fix kubeadm cilium manifest

---

Dockerfile

enh(Dockerfile): bump alpine repos used to install dependencies
